name: Sync to Gist

on:
  push:
    branches:
      - main

jobs:
  gist-sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Sync to Gist
      uses: Popsiclestick/gist-sync-action@v1.2.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gist_url: https://gist.github.com/BrunoArsioli/48d65f1f9611d8f43ca2f685456926da
        gist_title: python_interview_prep-intro.ipynb
        gist_description: Bridging Academia to Industry 
        github_file: notebooks/python_interview_prep-intro.ipynb
